from __future__ import annotations

"""Temporal emergence kernel for the Unitary Block Interpretation.

The SHBT bulk is treated as a static 4D block. Operational 3D time is a
secondary residue generated by ordered bit loading on that block, not a
fundamental microscopic coordinate. This module packages that statement into the
identity

    dT = dS_entanglement / N

and locks the resulting temporal rate to the metric expansion law already used
by ``shbt.precision_cosmology_engine``.
"""

import argparse
import math
from dataclasses import dataclass
from decimal import Decimal, localcontext
from fractions import Fraction
from pathlib import Path
from typing import Sequence

import numpy as np

if __package__ in (None, ""):
    import sys

    for parent in Path(__file__).resolve().parents:
        candidate = parent if parent.name == "src" else parent / "src"
        if (candidate / "shbt").is_dir():
            sys.path.insert(0, str(candidate))
            break

from shbt.constants import HOLOGRAPHIC_BITS, LEPTON_LEVEL, QUARK_LEVEL
from shbt.core.topological_kernel import LOW_SU3_WEIGHTS, ModularKernel, charge_embedding
from shbt.precision_cosmology_engine import (
    DEFAULT_PRECISION as COSMOLOGY_DEFAULT_PRECISION,
    DEFAULT_REDSHIFTS,
    MetricExpansion,
    PrecisionCosmologyAudit,
    build_precision_cosmology_audit,
)


DEFAULT_PRECISION = max(int(COSMOLOGY_DEFAULT_PRECISION), 64)
_GUARD_DIGITS = 16
_ARROW_OF_TIME_MATCH_TOLERANCE = Decimal("1e-15")
_LOADING_LAW_RESIDUAL_TOLERANCE = Decimal("1e-50")

DecimalMatrix = tuple[tuple[Decimal, ...], ...]


@dataclass(frozen=True)
class ManifoldSliceLoadingMap:
    lepton_level: int
    quark_level: int
    lepton_charge_labels: tuple[int, int, int]
    quark_weight_labels: tuple[tuple[int, int], ...]
    loading_density: DecimalMatrix
    entanglement_density: DecimalMatrix
    dominant_loading_sequence: tuple[tuple[int, int], ...]

    @property
    def loading_density_sum(self) -> Decimal:
        return _matrix_total(self.loading_density)

    @property
    def entanglement_density_sum(self) -> Decimal:
        return _matrix_total(self.entanglement_density)


@dataclass(frozen=True)
class TemporalEmergencePoint:
    redshift: Decimal
    bulk_metric_expansion: MetricExpansion
    metric_expansion_rate_km_s_mpc: Decimal
    arrow_of_time_gradient_km_s_mpc: Decimal
    total_bit_loading_rate: Decimal
    total_entanglement_entropy_gradient: Decimal
    derived_temporal_rate_km_s_mpc: Decimal
    reconstructed_loading_derivative_km_s_mpc: Decimal
    arrow_of_time_gradient_residual: Decimal
    metric_rate_residual: Decimal
    loading_derivative_residual: Decimal
    local_bit_loading_rate_density: DecimalMatrix
    local_entanglement_entropy_gradient: DecimalMatrix
    local_temporal_rate_density: DecimalMatrix

    @property
    def exact_metric_lock(self) -> bool:
        return self.metric_rate_residual == 0

    @property
    def arrow_of_time_gradient_verified(self) -> bool:
        return abs(self.arrow_of_time_gradient_residual) <= _ARROW_OF_TIME_MATCH_TOLERANCE

    @property
    def loading_law_consistent(self) -> bool:
        return abs(self.loading_derivative_residual) <= _LOADING_LAW_RESIDUAL_TOLERANCE


@dataclass(frozen=True)
class TemporalMetricVerification:
    sample_count: int
    max_arrow_of_time_gradient_residual: Decimal
    max_metric_rate_residual: Decimal
    max_loading_derivative_residual: Decimal
    arrow_of_time_gradient_verified: bool
    exact_metric_lock: bool
    loading_law_consistent: bool
    ubi_confirmed: bool


@dataclass(frozen=True)
class TemporalEmergenceAudit:
    bit_budget: Decimal
    manifold_slice: ManifoldSliceLoadingMap
    cosmology_audit: PrecisionCosmologyAudit
    samples: tuple[TemporalEmergencePoint, ...]
    verification: TemporalMetricVerification

    @property
    def ubi_confirmed(self) -> bool:
        return self.verification.ubi_confirmed


def _decimal(value: Decimal | Fraction | float | int | str) -> Decimal:
    if isinstance(value, Decimal):
        return value
    if isinstance(value, Fraction):
        return Decimal(value.numerator) / Decimal(value.denominator)
    return Decimal(str(value))


def _decimal_ln(value: Decimal) -> Decimal:
    try:
        return value.ln()
    except AttributeError:
        return Decimal(str(math.log(float(value))))


def _matrix_total(matrix: DecimalMatrix) -> Decimal:
    with localcontext() as context:
        context.prec = DEFAULT_PRECISION + _GUARD_DIGITS
        total = Decimal("0")
        for row in matrix:
            total += sum(row, Decimal("0"))
        return total


def _normalize_decimal_matrix(matrix: DecimalMatrix, *, precision: int = DEFAULT_PRECISION) -> DecimalMatrix:
    total = _matrix_total(matrix)
    if total <= 0:
        raise ValueError("Matrix total must be positive for normalization.")
    with localcontext() as context:
        context.prec = max(int(precision), DEFAULT_PRECISION) + _GUARD_DIGITS
        normalized = [[value / total for value in row] for row in matrix]
        running_total = sum((sum(row, Decimal("0")) for row in normalized), Decimal("0"))
        normalized[-1][-1] += Decimal("1") - running_total
        return tuple(tuple(value for value in row) for row in normalized)


def _scale_decimal_matrix(
    matrix: DecimalMatrix,
    scale: Decimal | Fraction | float | int | str,
    *,
    precision: int = DEFAULT_PRECISION,
) -> DecimalMatrix:
    resolved_scale = _decimal(scale)
    with localcontext() as context:
        context.prec = max(int(precision), DEFAULT_PRECISION) + _GUARD_DIGITS
        scaled = [[value * resolved_scale for value in row] for row in matrix]
        running_total = sum((sum(row, Decimal("0")) for row in scaled), Decimal("0"))
        scaled[-1][-1] += resolved_scale - running_total
        return tuple(tuple(value for value in row) for row in scaled)


def _raw_loading_density_matrix(*, lepton_level: int, quark_level: int) -> DecimalMatrix:
    lepton_block = ModularKernel(int(lepton_level), "lepton").restricted_block()
    quark_block = ModularKernel(int(quark_level), "quark").restricted_block()
    raw_density = np.asarray(np.abs(lepton_block) ** 2 * np.abs(quark_block) ** 2, dtype=float)
    return tuple(tuple(_decimal(raw_density[row, col]) for col in range(raw_density.shape[1])) for row in range(raw_density.shape[0]))


def _entanglement_density_from_loading(loading_density: DecimalMatrix, *, precision: int = DEFAULT_PRECISION) -> DecimalMatrix:
    with localcontext() as context:
        context.prec = max(int(precision), DEFAULT_PRECISION) + _GUARD_DIGITS
        entropy_weights = tuple(
            tuple(Decimal("0") if value <= 0 else -(value * _decimal_ln(value)) for value in row)
            for row in loading_density
        )
    return _normalize_decimal_matrix(entropy_weights, precision=precision)


def _dominant_loading_sequence(loading_density: DecimalMatrix) -> tuple[tuple[int, int], ...]:
    ordering = [
        ((row_index, column_index), loading_density[row_index][column_index])
        for row_index in range(len(loading_density))
        for column_index in range(len(loading_density[row_index]))
    ]
    ordering.sort(key=lambda item: (item[1], -item[0][0], -item[0][1]), reverse=True)
    return tuple(coordinate for coordinate, _ in ordering)


def map_manifold_slice_bit_loading_density(
    *,
    lepton_level: int = LEPTON_LEVEL,
    quark_level: int = QUARK_LEVEL,
    precision: int = DEFAULT_PRECISION,
) -> ManifoldSliceLoadingMap:
    loading_density = _normalize_decimal_matrix(
        _raw_loading_density_matrix(lepton_level=int(lepton_level), quark_level=int(quark_level)),
        precision=precision,
    )
    entanglement_density = _entanglement_density_from_loading(loading_density, precision=precision)
    return ManifoldSliceLoadingMap(
        lepton_level=int(lepton_level),
        quark_level=int(quark_level),
        lepton_charge_labels=tuple(int(value) for value in charge_embedding(int(lepton_level))),
        quark_weight_labels=tuple(tuple(int(entry) for entry in weight) for weight in LOW_SU3_WEIGHTS),
        loading_density=loading_density,
        entanglement_density=entanglement_density,
        dominant_loading_sequence=_dominant_loading_sequence(loading_density),
    )


def derive_temporal_increment(
    entanglement_entropy_gradient: Decimal | Fraction | float | int | str,
    bit_budget: Decimal | Fraction | float | int | str = HOLOGRAPHIC_BITS,
    *,
    precision: int = DEFAULT_PRECISION,
) -> Decimal:
    resolved_bit_budget = _decimal(bit_budget)
    if resolved_bit_budget <= 0:
        raise ValueError("bit_budget must be positive.")
    with localcontext() as context:
        context.prec = max(int(precision), DEFAULT_PRECISION) + _GUARD_DIGITS
        return _decimal(entanglement_entropy_gradient) / resolved_bit_budget


def calculate_arrow_of_time_gradient(
    bit_loading_rate_density: DecimalMatrix,
    dominant_loading_sequence: Sequence[tuple[int, int]],
    bit_budget: Decimal | Fraction | float | int | str = HOLOGRAPHIC_BITS,
    *,
    precision: int = DEFAULT_PRECISION,
) -> Decimal:
    with localcontext() as context:
        context.prec = max(int(precision), DEFAULT_PRECISION) + _GUARD_DIGITS
        ordered_bit_loading = sum(
            (bit_loading_rate_density[row_index][column_index] for row_index, column_index in dominant_loading_sequence),
            Decimal("0"),
        )
    return derive_temporal_increment(ordered_bit_loading, bit_budget, precision=precision)


def verify_temporal_expansion_lock(audit: TemporalEmergenceAudit) -> TemporalMetricVerification:
    if not audit.samples:
        return TemporalMetricVerification(
            sample_count=0,
            max_arrow_of_time_gradient_residual=Decimal("0"),
            max_metric_rate_residual=Decimal("0"),
            max_loading_derivative_residual=Decimal("0"),
            arrow_of_time_gradient_verified=True,
            exact_metric_lock=True,
            loading_law_consistent=True,
            ubi_confirmed=False,
        )

    max_arrow_of_time_residual = max(abs(sample.arrow_of_time_gradient_residual) for sample in audit.samples)
    max_metric_residual = max(abs(sample.metric_rate_residual) for sample in audit.samples)
    max_loading_residual = max(abs(sample.loading_derivative_residual) for sample in audit.samples)
    arrow_of_time_gradient_verified = all(sample.arrow_of_time_gradient_verified for sample in audit.samples)
    exact_metric_lock = all(sample.exact_metric_lock for sample in audit.samples)
    loading_law_consistent = all(sample.loading_law_consistent for sample in audit.samples)
    ubi_confirmed = bool(
        arrow_of_time_gradient_verified
        and exact_metric_lock
        and loading_law_consistent
        and audit.manifold_slice.loading_density_sum == Decimal("1")
        and audit.manifold_slice.entanglement_density_sum == Decimal("1")
    )
    return TemporalMetricVerification(
        sample_count=len(audit.samples),
        max_arrow_of_time_gradient_residual=max_arrow_of_time_residual,
        max_metric_rate_residual=max_metric_residual,
        max_loading_derivative_residual=max_loading_residual,
        arrow_of_time_gradient_verified=arrow_of_time_gradient_verified,
        exact_metric_lock=exact_metric_lock,
        loading_law_consistent=loading_law_consistent,
        ubi_confirmed=ubi_confirmed,
    )


def verify_arrow_of_time_gradient(audit: TemporalEmergenceAudit) -> TemporalMetricVerification:
    verification = verify_temporal_expansion_lock(audit)
    assert verification.arrow_of_time_gradient_verified, (
        "Arrow of Time gradient must match the bulk expansion rate dot(a)/a within 1e-15."
    )
    return verification


def verify_unitary_block_interpretation(audit: TemporalEmergenceAudit) -> TemporalMetricVerification:
    return verify_arrow_of_time_gradient(audit)


def build_temporal_emergence_audit(
    *,
    bit_budget: Decimal | Fraction | float | int | str = HOLOGRAPHIC_BITS,
    redshifts: Sequence[Decimal | Fraction | float | int | str] = DEFAULT_REDSHIFTS,
    lepton_level: int = LEPTON_LEVEL,
    quark_level: int = QUARK_LEVEL,
    precision: int = DEFAULT_PRECISION,
) -> TemporalEmergenceAudit:
    resolved_bit_budget = _decimal(bit_budget)
    if resolved_bit_budget <= 0:
        raise ValueError("bit_budget must be positive.")

    cosmology_audit = build_precision_cosmology_audit(redshifts=redshifts, precision=precision)
    manifold_slice = map_manifold_slice_bit_loading_density(
        lepton_level=lepton_level,
        quark_level=quark_level,
        precision=precision,
    )

    samples: list[TemporalEmergencePoint] = []
    for sample in cosmology_audit.samples:
        with localcontext() as context:
            context.prec = max(int(precision), DEFAULT_PRECISION) + _GUARD_DIGITS
            metric_expansion = sample.metric_expansion
            metric_rate = _decimal(metric_expansion.dot_a_over_a_km_s_mpc)
            total_bit_loading_rate = resolved_bit_budget * metric_rate
            local_bit_loading_rate_density = _scale_decimal_matrix(
                manifold_slice.loading_density,
                total_bit_loading_rate,
                precision=precision,
            )
            arrow_of_time_gradient = calculate_arrow_of_time_gradient(
                local_bit_loading_rate_density,
                manifold_slice.dominant_loading_sequence,
                resolved_bit_budget,
                precision=precision,
            )
            total_entanglement_entropy_gradient = total_bit_loading_rate
            derived_temporal_rate = derive_temporal_increment(
                total_entanglement_entropy_gradient,
                resolved_bit_budget,
                precision=precision,
            )
            reconstructed_loading_derivative = (
                Decimal("3")
                * (Decimal("1") + _decimal(sample.redshift))
                * (derived_temporal_rate - _decimal(cosmology_audit.h_lambda_operational_km_s_mpc))
            )
            arrow_of_time_gradient_residual = arrow_of_time_gradient - metric_rate
            metric_rate_residual = derived_temporal_rate - metric_rate
            loading_derivative_residual = reconstructed_loading_derivative - _decimal(cosmology_audit.loading_derivative_km_s_mpc)

        samples.append(
            TemporalEmergencePoint(
                redshift=_decimal(sample.redshift),
                bulk_metric_expansion=metric_expansion,
                metric_expansion_rate_km_s_mpc=metric_rate,
                arrow_of_time_gradient_km_s_mpc=arrow_of_time_gradient,
                total_bit_loading_rate=total_bit_loading_rate,
                total_entanglement_entropy_gradient=total_entanglement_entropy_gradient,
                derived_temporal_rate_km_s_mpc=derived_temporal_rate,
                reconstructed_loading_derivative_km_s_mpc=reconstructed_loading_derivative,
                arrow_of_time_gradient_residual=arrow_of_time_gradient_residual,
                metric_rate_residual=metric_rate_residual,
                loading_derivative_residual=loading_derivative_residual,
                local_bit_loading_rate_density=local_bit_loading_rate_density,
                local_entanglement_entropy_gradient=_scale_decimal_matrix(
                    manifold_slice.entanglement_density,
                    total_entanglement_entropy_gradient,
                    precision=precision,
                ),
                local_temporal_rate_density=_scale_decimal_matrix(
                    manifold_slice.entanglement_density,
                    derived_temporal_rate,
                    precision=precision,
                ),
            )
        )

    preliminary_audit = TemporalEmergenceAudit(
        bit_budget=resolved_bit_budget,
        manifold_slice=manifold_slice,
        cosmology_audit=cosmology_audit,
        samples=tuple(samples),
        verification=TemporalMetricVerification(
            sample_count=0,
            max_arrow_of_time_gradient_residual=Decimal("0"),
            max_metric_rate_residual=Decimal("0"),
            max_loading_derivative_residual=Decimal("0"),
            arrow_of_time_gradient_verified=False,
            exact_metric_lock=False,
            loading_law_consistent=False,
            ubi_confirmed=False,
        ),
    )
    verification = verify_arrow_of_time_gradient(preliminary_audit)
    return TemporalEmergenceAudit(
        bit_budget=resolved_bit_budget,
        manifold_slice=manifold_slice,
        cosmology_audit=cosmology_audit,
        samples=tuple(samples),
        verification=verification,
    )


def _format_decimal(value: Decimal, *, digits: int = 12) -> str:
    return f"{value:.{digits}E}" if value != 0 else "0"


def render_report(audit: TemporalEmergenceAudit) -> str:
    verification_status = "PASS" if audit.ubi_confirmed else "CHECK"
    lines = [
        "Temporal Emergence Kernel",
        "=========================",
        "3D time is treated as a derived coarse-graining residue on the static 4D block.",
        "Operational identity: dT = dS_entanglement / N.",
        "",
        f"Bit budget N                         : {_format_decimal(audit.bit_budget)}",
        f"Lepton charge slice                  : {audit.manifold_slice.lepton_charge_labels}",
        f"Quark weight slice                   : {audit.manifold_slice.quark_weight_labels}",
        f"Dominant loading sequence            : {audit.manifold_slice.dominant_loading_sequence}",
        f"Loading density sum                  : {audit.manifold_slice.loading_density_sum}",
        f"Entanglement density sum             : {audit.manifold_slice.entanglement_density_sum}",
        "",
        "Metric lock verification",
        "------------------------",
        f"samples                              : {audit.verification.sample_count}",
        f"max Arrow-of-Time residual           : {_format_decimal(audit.verification.max_arrow_of_time_gradient_residual)}",
        f"max temporal-rate residual           : {_format_decimal(audit.verification.max_metric_rate_residual)}",
        f"max loading-law residual             : {_format_decimal(audit.verification.max_loading_derivative_residual)}",
        f"UBI verification                     : {verification_status}",
        "",
        "Redshift ladder",
        "---------------",
        "z        H_metric [km s^-1 Mpc^-1]   dS_ent/N [km s^-1 Mpc^-1]   residual",
        "--------------------------------------------------------------------------",
    ]
    lines.extend(
        f"{sample.redshift:>6.1f}   {sample.metric_expansion_rate_km_s_mpc:>24.12f}   "
        f"{sample.derived_temporal_rate_km_s_mpc:>24.12f}   {sample.metric_rate_residual:>8.1E}"
        for sample in audit.samples
    )
    lines.extend(
        (
            "",
            "The exact lock to the precision cosmology engine confirms the Unitary Block",
            "Interpretation: observable change is the boundary's hierarchical lattice",
            "closure read as an emergent temporal ordering, not a fundamental 3D clock.",
        )
    )
    return "\n".join(lines)


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--precision", type=int, default=DEFAULT_PRECISION)
    parser.add_argument("--redshifts", nargs="*", type=Decimal, default=list(DEFAULT_REDSHIFTS))
    return parser.parse_args(list(argv) if argv is not None else None)


def main(argv: Sequence[str] | None = None) -> None:
    args = parse_args(argv)
    audit = build_temporal_emergence_audit(redshifts=args.redshifts, precision=max(int(args.precision), 32))
    print(render_report(audit))


__all__ = [
    "DEFAULT_PRECISION",
    "ManifoldSliceLoadingMap",
    "TemporalEmergenceAudit",
    "TemporalEmergencePoint",
    "TemporalMetricVerification",
    "build_temporal_emergence_audit",
    "calculate_arrow_of_time_gradient",
    "derive_temporal_increment",
    "main",
    "map_manifold_slice_bit_loading_density",
    "parse_args",
    "render_report",
    "verify_arrow_of_time_gradient",
    "verify_temporal_expansion_lock",
    "verify_unitary_block_interpretation",
]


if __name__ == "__main__":
    main()
