from __future__ import annotations

"""Thermodynamic time evolution for the SHBT bulk image.

This module treats time as a transport residue generated by entanglement
thermalization rather than as a static projection coordinate. The 26D boundary
is allowed to thermalize onto its 4D bulk image by iterating over the ordered
entanglement channels already disclosed by the temporal-emergence kernel.

At each transport iteration:

- a positive entanglement-entropy increment is deposited on the boundary,
- a mandatory bit-residue is generated from that increment, and
- the Arrow of Time is identified with the cumulative increase of the
  boundary/bulk entanglement complexity.

In this bookkeeping the Second Law is not an auxiliary postulate: it is the
statement that every transport step produces a non-negative bit residue.
"""

from dataclasses import dataclass
from decimal import Decimal, localcontext
from fractions import Fraction
from functools import cached_property

from shbt.constants import HOLOGRAPHIC_BITS, LEPTON_LEVEL, QUARK_LEVEL
from shbt.core.temporal_emergence_kernel import (
    DEFAULT_PRECISION as TEMPORAL_DEFAULT_PRECISION,
    ManifoldSliceLoadingMap,
    derive_temporal_increment,
    map_manifold_slice_bit_loading_density,
)


DEFAULT_PRECISION = max(int(TEMPORAL_DEFAULT_PRECISION), 64)
DEFAULT_BOUNDARY_DIMENSION = 26
DEFAULT_BULK_DIMENSION = 4
DEFAULT_ITERATION_COUNT = DEFAULT_BOUNDARY_DIMENSION
_GUARD_DIGITS = 16
_THERMODYNAMIC_TOLERANCE = Decimal("1e-30")
_RELATIVE_ACCOUNTING_TOLERANCE = Decimal("1e-60")


def _decimal(value: Decimal | Fraction | float | int | str) -> Decimal:
    if isinstance(value, Decimal):
        return value
    if isinstance(value, Fraction):
        return Decimal(value.numerator) / Decimal(value.denominator)
    return Decimal(str(value))


def _relative_residual(residual: Decimal, scale: Decimal) -> Decimal:
    magnitude = max(abs(scale), Decimal("1"))
    return abs(residual) / magnitude


@dataclass(frozen=True)
class ThermodynamicStep:
    iteration: int
    boundary_mode: tuple[int, int]
    mode_entanglement_weight: Decimal
    entropy_increment_bits: Decimal
    cumulative_boundary_entropy_bits: Decimal
    cumulative_bulk_entropy_bits: Decimal
    transport_bit_residue: Decimal
    complexity_increment: Decimal
    cumulative_entanglement_complexity: Decimal
    arrow_of_time_increment: Decimal
    cumulative_time: Decimal
    thermalization_fraction: Decimal
    second_law_residual: Decimal
    complexity_time_residual: Decimal

    @property
    def second_law_satisfied(self) -> bool:
        return bool(
            self.entropy_increment_bits > 0
            and self.transport_bit_residue > 0
            and _relative_residual(self.second_law_residual, self.entropy_increment_bits)
            <= _RELATIVE_ACCOUNTING_TOLERANCE
        )

    @property
    def arrow_of_time_positive(self) -> bool:
        return self.arrow_of_time_increment > 0 and self.cumulative_time > 0

    @property
    def complexity_increases(self) -> bool:
        return bool(
            self.complexity_increment > 0
            and self.cumulative_entanglement_complexity > 0
            and _relative_residual(self.complexity_time_residual, self.complexity_increment)
            <= _RELATIVE_ACCOUNTING_TOLERANCE
        )


@dataclass(frozen=True)
class ThermodynamicEvolution:
    boundary_dimension: int
    bulk_dimension: int
    bit_budget: Decimal
    manifold_slice: ManifoldSliceLoadingMap
    steps: tuple[ThermodynamicStep, ...]

    @property
    def final_boundary_entropy_bits(self) -> Decimal:
        return self.steps[-1].cumulative_boundary_entropy_bits

    @property
    def final_bulk_entropy_bits(self) -> Decimal:
        return self.steps[-1].cumulative_bulk_entropy_bits

    @property
    def final_entanglement_complexity(self) -> Decimal:
        return self.steps[-1].cumulative_entanglement_complexity

    @property
    def final_time(self) -> Decimal:
        return self.steps[-1].cumulative_time

    @property
    def monotonic_entropy_growth(self) -> bool:
        return bool(
            self.steps
            and all(step.second_law_satisfied for step in self.steps)
            and all(
                self.steps[index].cumulative_boundary_entropy_bits
                > self.steps[index - 1].cumulative_boundary_entropy_bits
                for index in range(1, len(self.steps))
            )
        )

    @property
    def arrow_of_time_emerges(self) -> bool:
        return bool(
            self.steps
            and all(step.arrow_of_time_positive for step in self.steps)
            and all(
                self.steps[index].cumulative_time > self.steps[index - 1].cumulative_time
                for index in range(1, len(self.steps))
            )
        )

    @property
    def complexity_monotonic(self) -> bool:
        return bool(
            self.steps
            and all(step.complexity_increases for step in self.steps)
            and all(
                self.steps[index].cumulative_entanglement_complexity
                > self.steps[index - 1].cumulative_entanglement_complexity
                for index in range(1, len(self.steps))
            )
        )

    @property
    def second_law_mandatory(self) -> bool:
        return all(step.second_law_satisfied for step in self.steps)

    @property
    def statement(self) -> str:
        return (
            "Time emerges as the monotonic thermodynamic residue of entanglement growth "
            "between the 26D boundary and the 4D bulk."
        )


class EntropyEngine:
    """Thermalize the holographic boundary into a time-directed bulk history."""

    def __init__(
        self,
        *,
        boundary_dimension: int = DEFAULT_BOUNDARY_DIMENSION,
        bulk_dimension: int = DEFAULT_BULK_DIMENSION,
        bit_budget: Decimal | Fraction | float | int | str = HOLOGRAPHIC_BITS,
        lepton_level: int = LEPTON_LEVEL,
        quark_level: int = QUARK_LEVEL,
        precision: int = DEFAULT_PRECISION,
    ) -> None:
        resolved_boundary_dimension = int(boundary_dimension)
        resolved_bulk_dimension = int(bulk_dimension)
        if resolved_boundary_dimension <= 0:
            raise ValueError("boundary_dimension must be positive.")
        if resolved_bulk_dimension <= 0:
            raise ValueError("bulk_dimension must be positive.")

        self.boundary_dimension = resolved_boundary_dimension
        self.bulk_dimension = resolved_bulk_dimension
        self.bit_budget = _decimal(bit_budget)
        self.lepton_level = int(lepton_level)
        self.quark_level = int(quark_level)
        self.precision = max(int(precision), DEFAULT_PRECISION)
        if self.bit_budget <= 0:
            raise ValueError("bit_budget must be positive.")

    @cached_property
    def manifold_slice(self) -> ManifoldSliceLoadingMap:
        return map_manifold_slice_bit_loading_density(
            lepton_level=self.lepton_level,
            quark_level=self.quark_level,
            precision=self.precision,
        )

    @cached_property
    def ordered_modes(self) -> tuple[tuple[int, int], ...]:
        return tuple(self.manifold_slice.dominant_loading_sequence)

    @cached_property
    def ordered_entanglement_weights(self) -> tuple[Decimal, ...]:
        return tuple(
            self.manifold_slice.entanglement_density[row_index][column_index]
            for row_index, column_index in self.ordered_modes
        )

    def simulate_time_evolution(self, *, iterations: int = DEFAULT_ITERATION_COUNT) -> ThermodynamicEvolution:
        resolved_iterations = int(iterations)
        if resolved_iterations <= 0:
            raise ValueError("iterations must be positive.")

        bridge_factor = Decimal(self.boundary_dimension * self.bulk_dimension)
        bulk_projection_factor = Decimal(self.bulk_dimension) / Decimal(self.boundary_dimension)
        cumulative_boundary_entropy = Decimal("0")
        cumulative_complexity = Decimal("0")
        cumulative_time = Decimal("0")
        steps: list[ThermodynamicStep] = []

        with localcontext() as context:
            context.prec = self.precision + _GUARD_DIGITS
            for iteration in range(1, resolved_iterations + 1):
                mode = self.ordered_modes[(iteration - 1) % len(self.ordered_modes)]
                mode_weight = self.ordered_entanglement_weights[(iteration - 1) % len(self.ordered_entanglement_weights)]
                remaining_entropy = self.bit_budget - cumulative_boundary_entropy
                entropy_increment = remaining_entropy * mode_weight
                transport_bit_residue = derive_temporal_increment(
                    entropy_increment,
                    self.bit_budget,
                    precision=self.precision,
                )
                arrow_of_time_increment = transport_bit_residue
                complexity_increment = arrow_of_time_increment * bridge_factor

                cumulative_boundary_entropy += entropy_increment
                cumulative_bulk_entropy = cumulative_boundary_entropy * bulk_projection_factor
                cumulative_complexity += complexity_increment
                cumulative_time += arrow_of_time_increment

                steps.append(
                    ThermodynamicStep(
                        iteration=iteration,
                        boundary_mode=mode,
                        mode_entanglement_weight=mode_weight,
                        entropy_increment_bits=entropy_increment,
                        cumulative_boundary_entropy_bits=cumulative_boundary_entropy,
                        cumulative_bulk_entropy_bits=cumulative_bulk_entropy,
                        transport_bit_residue=transport_bit_residue,
                        complexity_increment=complexity_increment,
                        cumulative_entanglement_complexity=cumulative_complexity,
                        arrow_of_time_increment=arrow_of_time_increment,
                        cumulative_time=cumulative_time,
                        thermalization_fraction=cumulative_boundary_entropy / self.bit_budget,
                        second_law_residual=entropy_increment - (transport_bit_residue * self.bit_budget),
                        complexity_time_residual=complexity_increment - (arrow_of_time_increment * bridge_factor),
                    )
                )

        return ThermodynamicEvolution(
            boundary_dimension=self.boundary_dimension,
            bulk_dimension=self.bulk_dimension,
            bit_budget=self.bit_budget,
            manifold_slice=self.manifold_slice,
            steps=tuple(steps),
        )

    def thermalize_boundary(self, *, iterations: int = DEFAULT_ITERATION_COUNT) -> ThermodynamicEvolution:
        return self.simulate_time_evolution(iterations=iterations)


def build_thermodynamic_audit(*, iterations: int = DEFAULT_ITERATION_COUNT, **kwargs: object) -> ThermodynamicEvolution:
    return EntropyEngine(**kwargs).simulate_time_evolution(iterations=iterations)


__all__ = [
    "DEFAULT_BOUNDARY_DIMENSION",
    "DEFAULT_BULK_DIMENSION",
    "DEFAULT_ITERATION_COUNT",
    "EntropyEngine",
    "ThermodynamicEvolution",
    "ThermodynamicStep",
    "build_thermodynamic_audit",
]
